package:
  name: pyfiglet
  version: "0.7.5"

source:
  fn: pyfiglet-0.7.5.tar.gz
  url: https://pypi.python.org/packages/a2/65/4e29896298591d748f5ce4e96642b8a0a876b64ed7226b5ae65fae81e5c9/pyfiglet-0.7.5.tar.gz
  md5: aa956f7af37926ab4b739c9ef87f3808
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyfiglet = pyfiglet:main
    #
    # Would create an entry point called pyfiglet that calls pyfiglet.main()

    - pyfiglet = pyfiglet:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - pyfiglet
    - pyfiglet.fonts

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - pyfiglet --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/pwaller/pyfiglet
  license: GNU General Public License v2 or later (GPLv2+)
  summary: 'Pure-python FIGlet implementation'
  license_family: GPL2

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
